server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/powerup_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: secret123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

service:
  user:
    url: http://user-ms:8080/api/v1